/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package ui.person;
import model.IntegerVerifier;
import model.StringVerifier;
import model.Person;
import model.PersonDirectory;
import java.awt.CardLayout;
import javax.swing.InputVerifier;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author aakashrajawat
 */
public class CreatePersonJPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form CreatePatientJPanel
     */
    private PersonDirectory personDirectory;
    private JPanel userProcessContainer;
    
    public CreatePersonJPanel(JPanel userProcessContainer,PersonDirectory personDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.personDirectory = personDirectory;
        addVerifiers();
    }
    
    private void addVerifiers() {
        InputVerifier integerVerifier = new IntegerVerifier();
        personAgeJTextField.setInputVerifier(integerVerifier);
        InputVerifier stringVerifier = new StringVerifier();
        pesonNameJTextField.setInputVerifier(stringVerifier);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personAgeJTextField = new javax.swing.JTextField();
        addPersonJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        patientNameJLabel = new javax.swing.JLabel();
        AgeJLabel = new javax.swing.JLabel();
        pesonNameJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        weightjLabel = new javax.swing.JLabel();
        personWeightJTextField = new javax.swing.JTextField();
        addressjLabel = new javax.swing.JLabel();
        cityjLabel = new javax.swing.JLabel();
        personAddressJTextField = new javax.swing.JTextField();
        personCityJTextField = new javax.swing.JTextField();
        personCommunityJTextField1 = new javax.swing.JLabel();
        personCommunityjComboBox1 = new javax.swing.JComboBox<>();
        personhospitalJTextField1 = new javax.swing.JLabel();
        personhospital = new javax.swing.JComboBox<>();
        persondoctorJTextField1 = new javax.swing.JLabel();
        persondoctor = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        setMinimumSize(new java.awt.Dimension(500, 700));
        setPreferredSize(new java.awt.Dimension(500, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        personAgeJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personAgeJTextFieldActionPerformed(evt);
            }
        });
        add(personAgeJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 119, 159, -1));

        addPersonJButton.setText("Create Profile");
        addPersonJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPersonJButtonActionPerformed(evt);
            }
        });
        add(addPersonJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 335, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Person Profile");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 28, 488, -1));

        patientNameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        patientNameJLabel.setText("Person Name: ");
        add(patientNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 87, 90, -1));

        AgeJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AgeJLabel.setText("Age : ");
        add(AgeJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 122, 90, -1));
        add(pesonNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 84, 159, -1));

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 335, 97, -1));

        weightjLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        weightjLabel.setText("Weight: ");
        add(weightjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 157, 90, -1));

        personWeightJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personWeightJTextFieldActionPerformed(evt);
            }
        });
        add(personWeightJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 154, 159, -1));

        addressjLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addressjLabel.setText("Address:");
        add(addressjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 186, 90, -1));

        cityjLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cityjLabel.setText("City:");
        add(cityjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 209, 90, -1));
        add(personAddressJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 183, 159, -1));

        personCityJTextField.setEditable(false);
        personCityJTextField.setText("Boston");
        add(personCityJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 206, 159, -1));

        personCommunityJTextField1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        personCommunityJTextField1.setText("Community:");
        add(personCommunityJTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 239, 90, -1));

        personCommunityjComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Roxbury", "Fenway", "Downtown", "Kenmore" }));
        personCommunityjComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personCommunityjComboBox1ActionPerformed(evt);
            }
        });
        add(personCommunityjComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 236, 159, -1));

        personhospitalJTextField1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        personhospitalJTextField1.setText("Hospital:");
        add(personhospitalJTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 268, 90, -1));

        personhospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personhospitalActionPerformed(evt);
            }
        });
        add(personhospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 265, 159, -1));

        persondoctorJTextField1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        persondoctorJTextField1.setText("Doctor:");
        add(persondoctorJTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 297, 90, -1));

        persondoctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Cardiologist", "Neurologist", "Gynachologist", "Dentist" }));
        persondoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persondoctorActionPerformed(evt);
            }
        });
        add(persondoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 294, 159, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/hardiksodhani/Desktop/v870-tang-36.jpg")); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(300, 300));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -780, 2380, 2530));
    }// </editor-fold>//GEN-END:initComponents

    private void addPersonJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPersonJButtonActionPerformed
        // TODO add your handling code here:
        if (checkBlankInput()==Boolean.TRUE)
        {
            Person person=personDirectory.createAndAddPerson();
            person.setPersonName(pesonNameJTextField.getText());
            person.setAge(Integer.parseInt(personAgeJTextField.getText()));
            person.setweight(Integer.parseInt(personWeightJTextField.getText()));
            person.setCommunity((String)personCommunityjComboBox1.getSelectedItem());
            person.setCity(personCityJTextField.getText());
            person.setAddress(personAddressJTextField.getText());
            person.setHospital((String)personhospital.getSelectedItem());
            JOptionPane.showMessageDialog(this, "Person added!!", "Update",
                    JOptionPane.INFORMATION_MESSAGE);
            clearFields();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please enter all values",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addPersonJButtonActionPerformed
    private void clearFields()
    {
        pesonNameJTextField.setText("");
        personAgeJTextField.setText("");
        personWeightJTextField.setText("");
        personAddressJTextField.setText("");
        
    }
    private Boolean checkBlankInput()
    {
        if(pesonNameJTextField.getText().length()==0
                ||personAgeJTextField.getText().length()==0)
        {
            return false;
        }
        else{
            return true;
        }
    }
    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void personWeightJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personWeightJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personWeightJTextFieldActionPerformed

    private void personCommunityjComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personCommunityjComboBox1ActionPerformed
        // TODO add your handling code here:
        if(personCommunityjComboBox1.getSelectedItem().equals("Roxbury")){
            personhospital.removeAllItems();

            personhospital.addItem("Boston Medical Center");
            personhospital.addItem("Brigham and Women's Hospital");
            personhospital.addItem("Massachusetts General Hospital");

        }

        else{
            if(personCommunityjComboBox1.getSelectedItem().equals("Fenway")){
                personhospital.removeAllItems();

                personhospital.addItem("Boston children's Hospital");
                personhospital.addItem("Emergency Department");
                personhospital.addItem("General Hospital");
            }
            else{
                personCommunityjComboBox1.removeAllItems();
                //txtHospital.addItem(null);
                personhospital.addItem("HRI Hospital");
                personhospital.addItem("Bournewood Hospital");
                personhospital.addItem("Lemuel Shattuck Hospital");
            }
        }
    }//GEN-LAST:event_personCommunityjComboBox1ActionPerformed

    private void personhospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personhospitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personhospitalActionPerformed

    private void persondoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persondoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_persondoctorActionPerformed

    private void personAgeJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personAgeJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personAgeJTextFieldActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeJLabel;
    private javax.swing.JButton addPersonJButton;
    private javax.swing.JLabel addressjLabel;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel cityjLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel patientNameJLabel;
    private javax.swing.JTextField personAddressJTextField;
    private javax.swing.JTextField personAgeJTextField;
    private javax.swing.JTextField personCityJTextField;
    private javax.swing.JLabel personCommunityJTextField1;
    private javax.swing.JComboBox<String> personCommunityjComboBox1;
    private javax.swing.JTextField personWeightJTextField;
    private javax.swing.JComboBox<String> persondoctor;
    private javax.swing.JLabel persondoctorJTextField1;
    private javax.swing.JComboBox<String> personhospital;
    private javax.swing.JLabel personhospitalJTextField1;
    private javax.swing.JTextField pesonNameJTextField;
    private javax.swing.JLabel weightjLabel;
    // End of variables declaration//GEN-END:variables
}
